### ISSUE TITLE
Парсер GPS

### ISSUE THREAD

**Issue by NoMonsters** [NoMonsters/Moving-robot#1]
Надо сделать парсре в соответствии с требованиями

**Comment by NoMonsters** [comment]
Переходим на другой формат сообщений. Вместо GNGLL будет **GNRMC**. Пример в docs

**Comment by PugachA** [comment]
Щас сдеалем

**Comment by PugachA** [comment]
http://geostar-navi.com/files/docs/geos3/geos_nmea_protocol_v3_0_rus.pdf

**Comment by Li2s** [comment]
Залил первую версию, надо потестить
