### ISSUE TITLE
Найти решение для работы со строками

### ISSUE THREAD

**Issue by PugachA** [NoMonsters/Moving-robot#11]
include <string.h> не работает

**Comment by PugachA** [comment]
попробовать данную библиотеку 
https://www.microchip.com/webdoc/AVRLibcReferenceManual/group__avr__pgmspace.html

**Comment by PugachA** [comment]
http://we.easyelectronics.ru/Soft/bystryy-parser-nmea.html еще один источник

**Comment by Li2s** [comment]
Мне кажется, не нужно

**Comment by Li2s** [comment]
Вообще работает
