### ISSUE TITLE
Сборка

### ISSUE THREAD

**Issue by NoMonsters** [NoMonsters/Moving-robot#4]
Оставить как есть сборочную папку или сделать так, чтобы можно было создавать проект прямо в source, а что не надо в .gitignore записать?

**Comment by PugachA** [comment]
Вась можно один gitignore сделать на весь проект просто абсолютные пути там прописать

**Comment by NoMonsters** [comment]
> 
> 
> Вась можно один gitignore сделать на весь проект просто абсолютные пути там прописать

Я так и сделал с начала, но когда удалил пустышку.txt, то он и папку удалил из индексации. Мне хотелось, чтобы она была в репозитории и её качали вместе со всем, чтобы исключить какие-то пропиздоны. Поэтому добавил просто просто игнор в саму папку, т.к. абсолютно пустной папка быть в гите не может.

**Comment by NoMonsters** [comment]
Оставлю как есть
